version: '3.7'

services:

  postgres:
    image: postgres:14.3
    restart: always
    container_name: ticketApp
    ports:
      - "5932:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticketAppDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
